apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  repositories: |
    - name: git-repo
      url: https://pscode.lioncloud.net/bodhi-platform/bodhi-aws.git
      type: git
      insecure: true
      insecureIgnoreHostKey: true
      sshPrivateKeySecret:
        name: git-repo-secret
        key: SSH_PRIVATE_KEY
