apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - kube-proxy-configmap.yaml.yaml
  - kube-proxy-daemonset.yaml
patchesStrategicMerge:
  - patches/service-account-annotations.yaml

    # - patches/service-account-annotations.yaml
# patchesJson6902:
#   - target:
#       version: v1 # apiVersion
#       kind: ServiceAccount
#       name: aws-node
#       namespace: kube-system
#     path: patches/service-account-annotations.yaml
