apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    app.kubernetes.io/instance: certificates
  name: superset-ingressgateway-certs
  namespace: istio-system
spec:
  secretName: superset-ingressgateway-certs
  issuerRef:
    name: gateways-issuer
    kind: ClusterIssuer
  commonName: <<__subdomain_superset__>>.<<__domain__>>
  dnsNames:
    - <<__subdomain_superset__>>.<<__domain__>>
    - add.bodhimlops.xyz
