apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cache-server
    app.kubernetes.io/component: ml-pipeline
    app.kubernetes.io/instance: pipelines
    app.kubernetes.io/name: kubeflow-pipelines
    application-crd-id: kubeflow-pipelines
  name: cache-server
  namespace: kubeflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cache-server
      app.kubernetes.io/component: ml-pipeline
      app.kubernetes.io/name: kubeflow-pipelines
      application-crd-id: kubeflow-pipelines
  template:
    metadata:
      labels:
        app: cache-server
        app.kubernetes.io/component: ml-pipeline
        app.kubernetes.io/name: kubeflow-pipelines
        application-crd-id: kubeflow-pipelines
    spec:
      containers:
        - args:
            - '--db_driver=$(DBCONFIG_DRIVER)'
            - '--db_host=$(DBCONFIG_HOST_NAME)'
            - '--db_port=$(DBCONFIG_PORT)'
            - '--db_name=$(DBCONFIG_DB_NAME)'
            - '--db_user=$(DBCONFIG_USER)'
            - '--db_password=$(DBCONFIG_PASSWORD)'
            - '--namespace_to_watch=$(NAMESPACE_TO_WATCH)'
          env:
            - name: DBCONFIG_DB_NAME
              valueFrom:
                configMapKeyRef:
                  key: DB_NAME_CACHE
                  name: pipelines-rds-config
            - name: DBCONFIG_HOST_NAME
              valueFrom:
                configMapKeyRef:
                  key: RDS_HOST
                  name: pipelines-rds-config
            - name: DBCONFIG_PORT
              valueFrom:
                configMapKeyRef:
                  key: RDS_PORT
                  name: pipelines-rds-config
            - name: DBCONFIG_USER
              valueFrom:
                secretKeyRef:
                  key: RDS_USERNAME
                  name: pipelines-rds-secret
            - name: DBCONFIG_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: RDS_PASSWORD
                  name: pipelines-rds-secret
            - name: NAMESPACE_TO_WATCH
              value: ''
            - name: CACHE_IMAGE
              valueFrom:
                configMapKeyRef:
                  key: cacheImage
                  name: pipeline-install-config
            - name: CACHE_NODE_RESTRICTIONS
              valueFrom:
                configMapKeyRef:
                  key: cacheNodeRestrictions
                  name: pipeline-install-config
            - name: DBCONFIG_DRIVER
              value: mysql
          image: 'gcr.io/ml-pipeline/cache-server:1.8.5'
          imagePullPolicy: Always
          name: server
          ports:
            - containerPort: 8443
              name: webhook-api
          volumeMounts:
            - mountPath: /etc/webhook/certs
              name: webhook-tls-certs
              readOnly: true
      serviceAccountName: kubeflow-pipelines-cache
      volumes:
        - name: webhook-tls-certs
          secret:
            secretName: webhook-server-tls
