kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: abhishek-kumar6
  namespace: abhishek-kumar6
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
