apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: bodhi-realm
  namespace: auth
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secret-store
  target:
    name: bodhi-realm
    template:
      data:
        bodhi-realm.json: |
          {{ .realm }}
  data:
  - secretKey: realm
    remoteRef:
      key:  bodhi-ask-test/bodhi-sc-88/prod
      property: realm
