apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-postgresql
  namespace: auth
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secret-store

  target:
    name: keycloak-postgresql
    creationPolicy: Owner

  data:
  - secretKey: password
    remoteRef:
      key:  bodhi-ask-test/bodhi-sc-88/prod
      property: postgresql-password

  - secretKey: postgres-password
    remoteRef:
      key: bodhi-ask-test/bodhi-sc-88/prod
      property: postgresql-postgres-password
