---
apiVersion: v1
kind: ConfigMap
metadata:
  name: inferenceservice-config
  namespace: kubeflow
data:
  ingress: |-
    {
        "ingressGateway" : "kubeflow/kubeflow-gateway",
        "ingressService" : "istio-ingressgateway.istio-system.svc.cluster.local",
        "localGateway" : "istio-system/cluster-local-gateway",
        "localGatewayService" : "cluster-local-gateway.istio-system.svc.cluster.local"
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kserve-config
  namespace: kubeflow
data:
  ingressGateway: kubeflow/kubeflow-gateway