apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mlflow-secret
  namespace: mlflow
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secret-store

  target:
    name: mlflow-secret
    creationPolicy: Owner
  data:
  - secretKey: RDS_USERNAME
    remoteRef:
      key:  <<__external_secret_name.mlflow.rds_username__>>
      property: RDS_USERNAME
  - secretKey: RDS_PASSWORD
    remoteRef:
      key:  <<__external_secret_name.mlflow.rds_password__>>
      property: RDS_PASSWORD
