apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: bodhi-realm
  namespace: auth
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secret-store
  target:
    name: bodhi-realm
    template:
      data:
        bodhi-realm.json: |
          {{ .realm }}
  data:
  - secretKey: realm
    remoteRef:
      key:  <<__external_secret_name.keycloak.bodhi_realm__>>
      property: realm
