apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-secret
  namespace: auth
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secret-store

  target:
    name: keycloak-secret
    creationPolicy: Owner

  data:
  - secretKey: admin-password
    remoteRef:
      key:  <<__external_secret_name.keycloak.admin_password__>>
      property: admin-password

  - secretKey: database-password
    remoteRef:
      key: <<__external_secret_name.keycloak.database_password__>>
      property: database-password
  
  - secretKey: management-password
    remoteRef:
      key: <<__external_secret_name.keycloak.management_password__>>
      property: management-password
      

