apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-postgresql
  namespace: auth
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secret-store

  target:
    name: keycloak-postgresql
    creationPolicy: Owner

  data:
  - secretKey: password
    remoteRef:
      key:  <<__external_secret_name.keycloak.postgresql_password__>>
      property: postgresql-password

  - secretKey: postgres-password
    remoteRef:
      key: <<__external_secret_name.keycloak.postgresql_postgres_password__>>
      property: postgresql-postgres-password
