apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: oauth2-proxy
  namespace: auth
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secret-store

  target:
    name: oauth2-proxy
    creationPolicy: Owner

  data:
  - secretKey: client-id
    remoteRef:
      key:  <<__external_secret_name.auth.oidc_client_id__>>
      property: client-id

  - secretKey: client-secret
    remoteRef:
      key: <<__external_secret_name.auth.oidc_client_secret__>>
      property: client-secret

  - secretKey: cookie-secret
    remoteRef:
      key: <<__external_secret_name.auth.oidc_cookie_secret__>>
      property: cookie-secret

