apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jupyter-web-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    #repoURL: <<__git_repo.url__>>
    repoURL: <<__git_repo.url__>>
    targetRevision: <<__git_repo.target_revision__>>
    path: deployment/distribution/kubeflow/notebooks/jupyter-web-app
    # kustomize:
    #   version: v4.0.5
    
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
