apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: deployment/distribution/argo-workflows/metallb
    #repoURL: <<__git_repo.url__>>
    repoURL: <<__git_repo.url__>>
    targetRevision: <<__git_repo.target_revision__>>
    
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
