apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/kubernetes-sigs/metrics-server/releases/download/v0.5.0/components.yaml # metrics server (needed for HPA)
- https://github.com/kubeflow/manifests/common/knative/knative-serving/overlays/gateways?ref=v1.6.1
- https://github.com/kubeflow/manifests/common/knative/knative-eventing/base?ref=v1.6.1
- https://github.com/kubeflow/manifests/common/istio-1-14/cluster-local-gateway/base?ref=v1.6.1
