kind: ConfigMap
apiVersion: v1
metadata:
  name: pipelines-rds-config
  namespace: kubeflow
data:
  DB_NAME_PIPELINES: mlpipeline
  DB_NAME_CACHE: cachedb
  DB_NAME_METADATA: metadb
  RDS_HOST: bodhicoreprodrds.cpzbtxmnoxjs.us-east-2.rds.amazonaws.com:3306
  RDS_PORT: "3306"
