kind: ConfigMap
apiVersion: v1
metadata:
  name: pipelines-s3-config
  namespace: kubeflow
data:
  REGION: us-east-2
  BUCKET_NAME: bodhi-ask-test-pipelines-bucket
  PIPELINE_FOLDER: pipelines
  PIPELINE_PATH: pipelines
