apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - psap-virtual-service.yaml
  - allow-all-ns-psap-authorization-policy.yaml
