apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/kubeflow/pipelines/manifests/kustomize/env/cert-manager/platform-agnostic-multi-user?ref=1.8.5 # tag=1.6.0
- s3-secret.yaml
# - cachingwebhook.yaml

# patchesStrategicMerge:
# - minio-aws-gateway-deployment.yaml