apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pipelines-s3-secret
  namespace: kubeflow
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secret-store

  target:
    name: pipelines-s3-secret
    creationPolicy: Owner
  data:
  - secretKey: S3_ACCESSKEY
    remoteRef:
      key:  <<__external_secret_name.kubeflow.s3_accesskey__>>
      property: S3_ACCESSKEY
  - secretKey: S3_SECRETKEY
    remoteRef:
      key:  <<__external_secret_name.kubeflow.s3_secretkey__>>
      property: S3_SECRETKEY
