apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: istio-system

resources:
- ./cluster-local-gateway/base
- ./istio-crds/base
- ./istio-install/base
- ./istio-namespace/base
- ./kubeflow-istio-resources/base
#- profile-overlay.yaml
#- profile.yaml