apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-secret
  namespace: auth
spec:
  backendType: secretsManager
  roleArn: arn:aws:iam::412674115502:role/bodhi-ask-test-external-secret
  data:
    - key: bodhi-ask-test/bodhi-sc-88/prod
      name: admin-password
      property: admin-password
    - key: bodhi-ask-test/bodhi-sc-88/prod
      name: database-password
      property: database-password
    - key: bodhi-ask-test/bodhi-sc-88/prod
      name: management-password
      property: management-password
