apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-postgresql
  namespace: auth
spec:
  backendType: secretsManager
  roleArn: arn:aws:iam::412674115502:role/bodhi-ask-test-external-secret
  data:
    - key: bodhi-ask-test/bodhi-sc-88/prod
      name: postgresql-password
      property: postgresql-password
    - key: bodhi-ask-test/bodhi-sc-88/prod
      name: postgresql-postgres-password
      property: postgresql-postgres-password
