apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: git-repo-secret
  namespace: argocd
  # labels:
  #   argocd.argoproj.io/secret-type: repository
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secret-store
  target:
    name: git-repo-secret
    creationPolicy: Owner
# spec:
#   backendType: secretsManager
#   roleArn: arn:aws:iam::412674115502:role/bodhi-ask-test-external-secret
  data:
  - secretKey: HTTPS_USERNAME
    remoteRef:
      key: bodhi-ask-test/bodhi-sc-88/prod-repo
      property: HTTPS_USERNAME
  - secretKey: HTTPS_PASSWORD
    remoteRef:
      key: bodhi-ask-test/bodhi-sc-88/prod-repo
      property: HTTPS_PASSWORD
        
