kind: SealedSecret
apiVersion: bitnami.com/v1alpha1
metadata:
  name: git-repo-secret
  namespace: argocd
  creationTimestamp: null
spec:
  template:
    metadata:
      name: git-repo-secret
      namespace: argocd
      creationTimestamp: null
    data: null
  encryptedData:
    SSH_PRIVATE_KEY: AgCeZLzQ5FIGylelvlkzFhMmxur63j3lCd2jwDQOxknTCR8Gpe9+mL7/jypCKFxzhplppsMQY5mZ1G7Q+3hoVXVOziFo462t7sYZ+W1/7NZzfAuPxbmI+XPCooTCkGtvci+KA82tBcCBRWicknDWj6BOERTZolcyyrf2NfnqHvhVSTIyvJvljgiUS209z3aBA3KDqRZ8iQDVSPdKldy42rTXyml56n92HjIdWFBMnE2cE/FHvrOBPZtv3br12/7lBO4nj61NGRD/0p5LLf9ukbPWek4K9M4f/0lFfGeCBugyfTM3mfPsKjQyBDN86EZQqZ7PKObIhL+t8psByHDaNwxzqSC8+9+9CS8DDOIi5TkDfoq7DdRirWwkiF4WxqzpDD1N/VN8l7bwMIqFx9SIUIWE4aV7Gs/i0yiTpxOgG6abFiK961L/bn4E0P6kJgMY7+cWM/l6saX3bXZ9rltKcFKrAyFg4RydoE3KodOjlgUucPh5aXdurWszxj7V5gqeP29RYF8fjvcfs11vtdOgmshUFMC8TyIuaIEutlvbYwXS79IbZ50v/C6Feu1raPhmXQvbBcUCiUQjkjXF1cLtJO4Qo5tpb8CdPS789M9cbFqf+raMNnQEdNJFe2ebgqeq/QIZaa33dlbmFr3L3g6F5FW9tgv8TQdPhg2jbjCe7T8dHhztaG003um/aD4X0HcG0oQyyLtaVjOqMUU/lr12CvRr71imoZuSgx7UIrmG22HmbmEWngtFgiV7CjRi2omZDh7vovCtb9ebRQr7RrZTh4k4xkL3Pmd9z/nfwWdX96MSDUndnOqDNPm1feETk9YfY+R3wqtiwysEpsAhLC5+mBSM3/rCAMzquRYtW5Okgz5bxJmhFkuGdUo6CRDi5Eh2T9/hKk69L/j1aGFjlkcNvvSe2YXVEAFXkIbxkAx6KSjmaRli0ktKWL0DcoLAFxXLRbLKcgpBETRTwoCFZgIn8BMzsS5iaOtwRAxMhfDMhHGEUBWiVOUjQXMmgvWUWVcAPfPIc9viKuvjJonWJt1SqQsdfvzOmhJVglOhRYGwYu1XzKoiFEf6T71ZU+MjY0i5xKa8Dzu0jLV6uS9QGpa+VDBAzX3Dn/wCXImFCxldljlyeBxDLnMB4wfSag7NiKdQgm74BaWmbDpjUgkq1CYi5upZ5Q3chmCNzwPhIwH1B5Ni54kEXB72NEky85Ziieee3pV0PJ6+maS+wExv09l3P5+/9jar/N6U0ufg2BnT1+1wsNqT
