apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - istio-spec.yaml
  - namespace.yaml
  - mutating-webhook-configuration.yaml

# patchesStrategicMerge:
#   - |-
#     apiVersion: admissionregistration.k8s.io/v1
#     kind: MutatingWebhookConfiguration
#     metadata:
#       name: istio-sidecar-injector
#       annotations:
#         admissions.enforcer/disabled: "true"