apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mlpipeline-minio-artifact
  namespace: kubeflow
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secret-store

  target:
    name: mlpipeline-minio-artifact
    creationPolicy: Owner
  data:
  - secretKey: accesskey
    remoteRef:
      key:  bodhi-ask-test/bodhi-sc-88/prod
      property: accesskey
  - secretKey: secretkey
    remoteRef:
      key:  bodhi-ask-test/bodhi-sc-88/prod
      property: secretkey
