apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/kubeflow/manifests/contrib/kserve/models-web-app/overlays/kubeflow?ref=3b93df774fa31fe8a79e9d68104bbddbfeb44d45

# images:
# - name: gcr.io/kfserving/kfserving-controller
#   newName: gcr.io/kfserving/kfserving-controller
#   newTag: v0.5.1
  # digest: sha256:321f35c2cd934d449f9e1308ca45a8c9a92190bec83a33b37a18a6b4b649506a
