apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-events
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: deployment/distribution/argo-events/overlays/production
    #repoURL: https://pscode.lioncloud.net/bodhi-platform/bodhi-aws.git
    repoURL: https://pscode.lioncloud.net/bodhi-platform/bodhi-aws.git
    targetRevision: main
    
    
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
