apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-eks-resources
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://pscode.lioncloud.net/bodhi-platform/bodhi-aws.git
    targetRevision: main
    path: deployment/distribution/aws-eks-resources
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
