apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-operator
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://charts.external-secrets.io
    targetRevision: 0.5.9
    chart: external-secrets
    helm:
      parameters:
      - name: serviceAccount.annotations.eks\.amazonaws\.com/role-arn
        value: arn:aws:iam::412674115502:role/bodhi-ask-test-external-secret
      - name: clusterName
        value: bodhi-ask-test
      - name: vpcId
        value: vpc-00cd8f970d10a9ac9
      - name: region
        value: us-east-2
      - name: serviceAccount.create
        value: "true"
      - name: installCRDs
        value: "true"
      - name: crds.createClusterExternalSecret
        value: "true"
      - name: crds.createClusterSecretStore
        value: "true"
      - name: rbac.create
        value: "true"
      - name: resources.limits.cpu
        value: 100m
      - name: resources.limits.memory
        value: 300Mi
      - name: resources.requests.cpu
        value: 100m
      - name: resources.requests.memory
        value: 300Mi

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
