apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jupyter-web-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    #repoURL: https://pscode.lioncloud.net/bodhi-platform/bodhi-aws.git
    repoURL: https://pscode.lioncloud.net/bodhi-platform/bodhi-aws.git
    targetRevision: main
    path: deployment/distribution/kubeflow/notebooks/jupyter-web-app
    # kustomize:
    #   version: v4.0.5
    
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
