apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlflow
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: mlflow
    server: https://kubernetes.default.svc
  project: default
  source:
    #repoURL: https://pscode.lioncloud.net/bodhi-platform/bodhi-aws.git
    repoURL: https://pscode.lioncloud.net/bodhi-platform/bodhi-aws.git
    targetRevision: main
    path: deployment/distribution/mlflow
    # kustomize:
    #   version: v4.0.5
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
