apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: git-repo-secret
  namespace: argocd
  # labels:
  #   argocd.argoproj.io/secret-type: repository
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secret-store
  target:
    name: git-repo-secret
    creationPolicy: Owner
# spec:
#   backendType: <<__external_secrets.backend_type__>>
#   roleArn: <<__role_arn.external_secrets.argocd__>>
  data:
  - secretKey: HTTPS_USERNAME
    remoteRef:
      key: <<__external_secret_name.git_repo.https_username__>>
      property: HTTPS_USERNAME
  - secretKey: HTTPS_PASSWORD
    remoteRef:
      key: <<__external_secret_name.git_repo.https_password__>>
      property: HTTPS_PASSWORD
        
