# - op: add
#   path: /metadata/annotations
#   value:
#     eks.amazonaws.com/role-arn: arn:aws:iam::412674115502:role/bodhi-ask-test-eks-cni
# ---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: aws-node
  namespace: kube-system
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::412674115502:role/bodhi-ask-test-eks-cni
