apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - deployment.yaml
  - allow-all-ns-forecastui-authorization-policy.yaml
  - forecastui-virtual-service.yaml
  - access.yaml
