kind: ConfigMap
apiVersion: v1
metadata:
  name: mlflow-config
data:
  DB_NAME: mlflow
  RDS_HOST: bodhicoreprodrds.cpzbtxmnoxjs.us-east-2.rds.amazonaws.com:3306
  RDS_PORT: "3306"
  ARTIFACT_S3_BUCKET: bodhi-ask-test-mlfow-bucket
  ARTIFACT_S3_KEY_PREFIX: mlflow/experiments
