apiVersion: batch/v1
kind: Job
metadata:
  name: create-mlflow-database
  namespace: mlflow
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: 'false'
    spec:
      containers:
      - name: create-mlflow-database
        image: kschriek/mysql-db-creator
        env:
        - name: HOST
          valueFrom:
            configMapKeyRef:
              name: mlflow-config
              key: RDS_HOST
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: mlflow-config
              key: RDS_PORT
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: mlflow-secret
              key: RDS_USERNAME
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: mlflow-secret
              key: RDS_PASSWORD
        - name: DATABASE
          valueFrom:
            configMapKeyRef:
              name: mlflow-config
              key: DB_NAME
      restartPolicy: Never
  backoffLimit: 5
