apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - github.com/kubeflow/manifests/common/kubeflow-namespace/base

commonAnnotations:
  iam.amazonaws.com/permitted: "arn:aws:iam::<<__aws_account_id__>>:role/.*"
