apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bodhi-core
  namespace: argocd
spec:
  project: default
  source:
    #repoURL: https://pscode.lioncloud.net/bodhi-platform/bodhi-aws.git
    repoURL: https://pscode.lioncloud.net/bodhi-platform/bodhi-aws.git
    targetRevision: main
    path: deployment/distribution
    # kustomize:
    #   version: v4.0.5
    
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
