apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets
  namespace: kube-system
  annotations:
    eks.amazonaws.com/role-arn: <<__role_arn.external_secrets__>>
  labels:
    name: kubernetes-external-secrets
