apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow

resources:
- https://github.com/kubeflow/katib/manifests/v1beta1/installs/katib-with-kubeflow?ref=v0.14.0
- rds-secret.yaml
- rds-configmap.yaml
- database-creation-job.yaml

patchesStrategicMerge:
- patches/remove-mysql-resources.yaml
- patches/patch-db-manager.yaml
