apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: bodhi-realm
  namespace: auth
spec:
  backendType: <<__external_secrets.backend_type__>>
  roleArn: <<__role_arn.external_secrets.auth__>>
  data:
    - key: <<__external_secret_name.keycloak.bodhi_realm__>>
      name: realm
      property: realm
  kvVersion: 2
  template:
    data:
      bodhi-realm.json: |
        <%= Buffer.from(JSON.stringify(JSON.parse(data.realm).config)).toString("base64") %>

#<%= Buffer.from(JSON.stringify(JSON.parse(JSON.parse(data.realm)).config)).toString("base64") %>
