apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-secret
  namespace: auth
spec:
  backendType: <<__external_secrets.backend_type__>>
  roleArn: <<__role_arn.external_secrets.auth__>>
  data:
    - key: <<__external_secret_name.keycloak.admin_password__>>
      name: admin-password
      property: admin-password
    - key: <<__external_secret_name.keycloak.database_password__>>
      name: database-password
      property: database-password
    - key: <<__external_secret_name.keycloak.management_password__>>
      name: management-password
      property: management-password
