apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-postgresql
  namespace: auth
spec:
  backendType: <<__external_secrets.backend_type__>>
  roleArn: <<__role_arn.external_secrets.auth__>>
  data:
    - key: <<__external_secret_name.keycloak.postgresql_password__>>
      name: postgresql-password
      property: postgresql-password
    - key: <<__external_secret_name.keycloak.postgresql_postgres_password__>>
      name: postgresql-postgres-password
      property: postgresql-postgres-password
