apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/kubeflow/manifests/contrib/kserve/kserve?ref=v1.6.1
- https://github.com/kubeflow/manifests/contrib/kserve/models-web-app/overlays/kubeflow?ref=v1.6.1
- auth-policy.yaml

patchesStrategicMerge:
- patches/inferenceservice-config.yaml