apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-admin-secret
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secret-store

  target:
    name: grafana-admin-secret
    creationPolicy: Owner

  data:
  # name of the SECRET in the Azure KV (no prefix is by default a SECRET)
  - secretKey: admin-user
    remoteRef:
      key:  bodhi-ask-test/bodhi-sc-88/prod
      property: admin-user

  # explicit type and name of secret in the Azure KV
  - secretKey: admin-password
    remoteRef:
      key: bodhi-ask-test/bodhi-sc-88/prod
      property: admin-password