apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  labels:
    app.kubernetes.io/instance: external-secrets
  name: aws-secret-store
spec:
  provider:
    aws:
      region: us-east-2
      service: SecretsManager
      #role: arn:aws:iam::412674115502:role/bodhi-ask-test-external-secret
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: aws-credentials
            key: username
            namespace: kube-system
          secretAccessKeySecretRef:
            name: aws-credentials
            key: password
            namespace: kube-system
        jwt:
          serviceAccountRef:
            name: external-secrets
            namespace: kube-system