apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets
  namespace: kube-system
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::412674115502:role/bodhi-ask-test-external-secret
  labels:
    name: kubernetes-external-secrets
