apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  name: auth-ingressgateway-certs
  namespace: istio-system
spec:
  backendType: secretsManager
  template:
    type: kubernetes.io/tls
  roleArn: arn:aws:iam::412674115502:role/bodhi-ask-test-external-secret
  data:
    - key: bodhi-ask-test/bodhi-sc-88/prod
      name: ca.crt
    - key: bodhi-ask-test/bodhi-sc-88/prod
      name: tls.crt
    - key: bodhi-ask-test/bodhi-sc-88/prod
      name: tls.key
