apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: oauth2-proxy
  namespace: auth
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secret-store

  target:
    name: oauth2-proxy
    creationPolicy: Owner

  data:
  - secretKey: client-id
    remoteRef:
      key:  bodhi-ask-test/bodhi-sc-88/prod
      property: client-id

  - secretKey: client-secret
    remoteRef:
      key: bodhi-ask-test/bodhi-sc-88/prod
      property: client-secret

  - secretKey: cookie-secret
    remoteRef:
      key: bodhi-ask-test/bodhi-sc-88/prod
      property: cookie-secret

